// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from trade.proto

package com.xx.xxx.jcproto;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.ByteString;
import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;
import com.dyuproject.protostuff.UninitializedMessageException;

public final class TRADE_REQ_RSP_BB implements Externalizable, Message<TRADE_REQ_RSP_BB>
{

    public static Schema<TRADE_REQ_RSP_BB> getSchema()
    {
        return SCHEMA;
    }

    public static TRADE_REQ_RSP_BB getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final TRADE_REQ_RSP_BB DEFAULT_INSTANCE = new TRADE_REQ_RSP_BB();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    String accountID;
    ByteString rspmsg;
    String rspcode;

    public TRADE_REQ_RSP_BB()
    {
        
    }

    public TRADE_REQ_RSP_BB(
        String accountID,
        ByteString rspmsg,
        String rspcode
    )
    {
        this.accountID = accountID;
        this.rspmsg = rspmsg;
        this.rspcode = rspcode;
    }

    // getters and setters

    // accountID

    public String getAccountID()
    {
        return accountID;
    }

    public void setAccountID(String accountID)
    {
        this.accountID = accountID;
    }

    // rspmsg

    public ByteString getRspmsg()
    {
        return rspmsg;
    }

    public void setRspmsg(ByteString rspmsg)
    {
        this.rspmsg = rspmsg;
    }

    // rspcode

    public String getRspcode()
    {
        return rspcode;
    }

    public void setRspcode(String rspcode)
    {
        this.rspcode = rspcode;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<TRADE_REQ_RSP_BB> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<TRADE_REQ_RSP_BB> SCHEMA = new Schema<TRADE_REQ_RSP_BB>()
    {
        // schema methods

        public TRADE_REQ_RSP_BB newMessage()
        {
            return new TRADE_REQ_RSP_BB();
        }

        public Class<TRADE_REQ_RSP_BB> typeClass()
        {
            return TRADE_REQ_RSP_BB.class;
        }

        public String messageName()
        {
            return TRADE_REQ_RSP_BB.class.getSimpleName();
        }

        public String messageFullName()
        {
            return TRADE_REQ_RSP_BB.class.getName();
        }

        public boolean isInitialized(TRADE_REQ_RSP_BB message)
        {
            return 
                message.accountID != null 
                && message.rspmsg != null 
                && message.rspcode != null;
        }

        public void mergeFrom(Input input, TRADE_REQ_RSP_BB message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        message.accountID = input.readString();
                        break;
                    case 3:
                        message.rspmsg = input.readBytes();
                        break;
                    case 21:
                        message.rspcode = input.readString();
                        break;
                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, TRADE_REQ_RSP_BB message) throws IOException
        {
            if(message.accountID == null)
                throw new UninitializedMessageException(message);
            output.writeString(1, message.accountID, false);

            if(message.rspmsg == null)
                throw new UninitializedMessageException(message);
            output.writeBytes(3, message.rspmsg, false);

            if(message.rspcode == null)
                throw new UninitializedMessageException(message);
            output.writeString(21, message.rspcode, false);
        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "accountID";
                case 3: return "rspmsg";
                case 21: return "rspcode";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("accountID", 1);
            fieldMap.put("rspmsg", 3);
            fieldMap.put("rspcode", 21);
        }
    };
    
}
