// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from trade.proto

package com.xx.xxx.jcproto;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;
import com.dyuproject.protostuff.UninitializedMessageException;

public final class TRADE_REQ_UPDATE_PWD implements Externalizable, Message<TRADE_REQ_UPDATE_PWD>
{

    public static Schema<TRADE_REQ_UPDATE_PWD> getSchema()
    {
        return SCHEMA;
    }

    public static TRADE_REQ_UPDATE_PWD getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final TRADE_REQ_UPDATE_PWD DEFAULT_INSTANCE = new TRADE_REQ_UPDATE_PWD();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    String brokerID;
    String accountID;
    String oldPassword;
    String newPassword;
    String currencyID;

    public TRADE_REQ_UPDATE_PWD()
    {
        
    }

    public TRADE_REQ_UPDATE_PWD(
        String brokerID,
        String accountID,
        String oldPassword,
        String newPassword,
        String currencyID
    )
    {
        this.brokerID = brokerID;
        this.accountID = accountID;
        this.oldPassword = oldPassword;
        this.newPassword = newPassword;
        this.currencyID = currencyID;
    }

    // getters and setters

    // brokerID

    public String getBrokerID()
    {
        return brokerID;
    }

    public void setBrokerID(String brokerID)
    {
        this.brokerID = brokerID;
    }

    // accountID

    public String getAccountID()
    {
        return accountID;
    }

    public void setAccountID(String accountID)
    {
        this.accountID = accountID;
    }

    // oldPassword

    public String getOldPassword()
    {
        return oldPassword;
    }

    public void setOldPassword(String oldPassword)
    {
        this.oldPassword = oldPassword;
    }

    // newPassword

    public String getNewPassword()
    {
        return newPassword;
    }

    public void setNewPassword(String newPassword)
    {
        this.newPassword = newPassword;
    }

    // currencyID

    public String getCurrencyID()
    {
        return currencyID;
    }

    public void setCurrencyID(String currencyID)
    {
        this.currencyID = currencyID;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<TRADE_REQ_UPDATE_PWD> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<TRADE_REQ_UPDATE_PWD> SCHEMA = new Schema<TRADE_REQ_UPDATE_PWD>()
    {
        // schema methods

        public TRADE_REQ_UPDATE_PWD newMessage()
        {
            return new TRADE_REQ_UPDATE_PWD();
        }

        public Class<TRADE_REQ_UPDATE_PWD> typeClass()
        {
            return TRADE_REQ_UPDATE_PWD.class;
        }

        public String messageName()
        {
            return TRADE_REQ_UPDATE_PWD.class.getSimpleName();
        }

        public String messageFullName()
        {
            return TRADE_REQ_UPDATE_PWD.class.getName();
        }

        public boolean isInitialized(TRADE_REQ_UPDATE_PWD message)
        {
            return 
                message.brokerID != null 
                && message.accountID != null 
                && message.oldPassword != null 
                && message.newPassword != null 
                && message.currencyID != null;
        }

        public void mergeFrom(Input input, TRADE_REQ_UPDATE_PWD message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        message.brokerID = input.readString();
                        break;
                    case 2:
                        message.accountID = input.readString();
                        break;
                    case 3:
                        message.oldPassword = input.readString();
                        break;
                    case 4:
                        message.newPassword = input.readString();
                        break;
                    case 5:
                        message.currencyID = input.readString();
                        break;
                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, TRADE_REQ_UPDATE_PWD message) throws IOException
        {
            if(message.brokerID == null)
                throw new UninitializedMessageException(message);
            output.writeString(1, message.brokerID, false);

            if(message.accountID == null)
                throw new UninitializedMessageException(message);
            output.writeString(2, message.accountID, false);

            if(message.oldPassword == null)
                throw new UninitializedMessageException(message);
            output.writeString(3, message.oldPassword, false);

            if(message.newPassword == null)
                throw new UninitializedMessageException(message);
            output.writeString(4, message.newPassword, false);

            if(message.currencyID == null)
                throw new UninitializedMessageException(message);
            output.writeString(5, message.currencyID, false);
        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "brokerID";
                case 2: return "accountID";
                case 3: return "oldPassword";
                case 4: return "newPassword";
                case 5: return "currencyID";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("brokerID", 1);
            fieldMap.put("accountID", 2);
            fieldMap.put("oldPassword", 3);
            fieldMap.put("newPassword", 4);
            fieldMap.put("currencyID", 5);
        }
    };
    
}
