// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from trade.proto

package com.xx.xxx.jcproto;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class TRADE_REQ_LOGOUT implements Externalizable, Message<TRADE_REQ_LOGOUT>
{

    public static Schema<TRADE_REQ_LOGOUT> getSchema()
    {
        return SCHEMA;
    }

    public static TRADE_REQ_LOGOUT getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final TRADE_REQ_LOGOUT DEFAULT_INSTANCE = new TRADE_REQ_LOGOUT();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    String brokerID;
    String userID;

    public TRADE_REQ_LOGOUT()
    {
        
    }

    // getters and setters

    // brokerID

    public String getBrokerID()
    {
        return brokerID;
    }

    public void setBrokerID(String brokerID)
    {
        this.brokerID = brokerID;
    }

    // userID

    public String getUserID()
    {
        return userID;
    }

    public void setUserID(String userID)
    {
        this.userID = userID;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<TRADE_REQ_LOGOUT> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<TRADE_REQ_LOGOUT> SCHEMA = new Schema<TRADE_REQ_LOGOUT>()
    {
        // schema methods

        public TRADE_REQ_LOGOUT newMessage()
        {
            return new TRADE_REQ_LOGOUT();
        }

        public Class<TRADE_REQ_LOGOUT> typeClass()
        {
            return TRADE_REQ_LOGOUT.class;
        }

        public String messageName()
        {
            return TRADE_REQ_LOGOUT.class.getSimpleName();
        }

        public String messageFullName()
        {
            return TRADE_REQ_LOGOUT.class.getName();
        }

        public boolean isInitialized(TRADE_REQ_LOGOUT message)
        {
            return true;
        }

        public void mergeFrom(Input input, TRADE_REQ_LOGOUT message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        message.brokerID = input.readString();
                        break;
                    case 2:
                        message.userID = input.readString();
                        break;
                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, TRADE_REQ_LOGOUT message) throws IOException
        {
            if(message.brokerID != null)
                output.writeString(1, message.brokerID, false);

            if(message.userID != null)
                output.writeString(2, message.userID, false);
        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "brokerID";
                case 2: return "userID";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("brokerID", 1);
            fieldMap.put("userID", 2);
        }
    };
    
}
