// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from base.proto

package com.xx.xxx.jcproto.base;

public enum EnumMsgID implements com.dyuproject.protostuff.EnumLite<EnumMsgID>
{
    MSG_REQUEST(1),
    MSG_RESPONSE(2),
    MSG_LOGINREQ(3),
    MSG_LOGINRSP(4);
    
    public final int number;
    
    private EnumMsgID (int number)
    {
        this.number = number;
    }
    
    public int getNumber()
    {
        return number;
    }
    
    public static EnumMsgID valueOf(int number)
    {
        switch(number) 
        {
            case 1: return MSG_REQUEST;
            case 2: return MSG_RESPONSE;
            case 3: return MSG_LOGINREQ;
            case 4: return MSG_LOGINRSP;
            default: return null;
        }
    }
}
